---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/static/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/.nuxt"
  working_dir: "/.nuxt"
  instant_preview_command: npm run dev
